# Generated by Django 4.2.1 on 2025-01-15 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=126, null=True)),
                ('breed', models.CharField(blank=True, max_length=126, null=True)),
                ('health_status', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('BAD', 'Bad')], null=True)),
                ('species', models.CharField(blank=True, choices=[('DOG', 'dog'), ('CAT', 'cat')], null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ADOPTED', 'Adopted'), ('REJECTED', 'Rejected')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
