# Generated by Django 4.2.1 on 2025-01-15 10:00

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=django_fsm.FSMIntegerField(default=0),
        ),
    ]
