# Generated by Django 4.2.1 on 2025-01-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_animal_status"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userprofile",
            managers=[],
        ),
    ]
